import { ArrowUpRight, MessageCircleMore } from "lucide-react";
import { citations } from "../ui/content";
import type { Citation } from "../types/onboarding";

type Props = { activeCitationId: number; activeSource: Citation; onSelectCitation: (citationId: number) => void };

export function CitationProof({ activeCitationId, activeSource, onSelectCitation }: Props) {
  return <section className="proof-section" id="trust"><div className="proof-header reveal"><p className="eyebrow eyebrow-light">The citation thread</p><h2>Every answer leaves a trail you can inspect.</h2><p>The chat never asks you to take its word for it. Select a citation to move straight into the original material.</p></div><div className="proof-workspace reveal"><div className="workspace-source"><div className="workspace-bar"><span>Algorithms.pdf</span><span>{activeSource.page}</span></div><div className="paper-content"><p>CHAPTER THREE</p><h3>{activeSource.title}</h3><div className="paper-rule" /><p className="passage"><mark>{activeSource.text}</mark></p><p className="ghost-copy">The surrounding context stays visible, so a citation is never separated from the idea that gives it meaning.</p><span className="source-anchor">{activeSource.id}</span></div></div><div className="citation-thread" aria-hidden="true"><i>{activeSource.id}</i></div><div className="workspace-chat"><div className="chat-title"><MessageCircleMore size={17} strokeWidth={1} /> Study conversation</div><div className="chat-question"><span>You</span><p>Why does balance matter here?</p></div><div className="chat-answer"><span>NotesRAG</span><p>It keeps core operations logarithmic as the tree grows, rather than allowing one path to become disproportionately long. <button onClick={() => onSelectCitation(2)}>2</button></p></div><div className="citation-list">{citations.map((citation) => <button className={activeCitationId === citation.id ? "citation-item active" : "citation-item"} onClick={() => onSelectCitation(citation.id)} key={citation.id}><span>{citation.id}</span><div><strong>{citation.page}</strong><small>{citation.title}</small></div><ArrowUpRight size={15} strokeWidth={1} /></button>)}</div></div></div></section>;
}
